[package]
name = "faddeeva"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
native = ["faddeeva-sys"]

[dependencies]
faddeeva-sys = { path = "../faddeeva-sys", optional = true }
num-complex = "0.4"